import fs from "fs-extra";
import path from "node:path";
import type { DrmConfig, FeatureFlags } from "./types";
import { defaultConfig, validateConfig, saveConfig } from "./config/schema";

/**
 * Resolves the desktop-app template directory. Prefers the copy bundled
 * into this package at build time (`templates/desktop-app`, see
 * scripts/copy-template.js), and falls back to the sibling workspace
 * package for monorepo-local development before that copy exists.
 */
export function resolveTemplateDir(): string {
  const bundled = path.join(__dirname, "..", "..", "templates", "desktop-app");
  if (fs.existsSync(bundled)) return bundled;

  const monorepoSibling = path.join(__dirname, "..", "..", "..", "desktop-app");
  if (fs.existsSync(monorepoSibling)) return monorepoSibling;

  throw new Error(
    "Could not locate the desktop-app template. Run `npm run build` in packages/lib first."
  );
}

function slugify(name: string): string {
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return slug || "drm-wrap-app";
}

/** Rewrites the copied template's package.json name/description and electron-builder.yml appId/productName to match appName. */
export async function personalizeGeneratedProject(targetDir: string, appName: string): Promise<void> {
  const slug = slugify(appName);

  const packageJsonPath = path.join(targetDir, "package.json");
  if (await fs.pathExists(packageJsonPath)) {
    const pkg = await fs.readJson(packageJsonPath);
    pkg.name = slug;
    pkg.description = `${appName} — generated by drm-wrap`;
    await fs.writeJson(packageJsonPath, pkg, { spaces: 2 });
  }

  const builderConfigPath = path.join(targetDir, "electron-builder.yml");
  if (await fs.pathExists(builderConfigPath)) {
    let contents = await fs.readFile(builderConfigPath, "utf8");
    contents = contents.replace(/^appId: .*$/m, `appId: com.drmwrap.${slug}`);
    contents = contents.replace(/^productName: .*$/m, `productName: ${appName}`);
    await fs.writeFile(builderConfigPath, contents, "utf8");
  }
}

export interface ScaffoldOptions {
  targetDir: string;
  appName: string;
  baseUrl: string;
  features: FeatureFlags;
  /** Absolute path to a custom logo image to copy over public/logo.png. Omit to keep the default. */
  logoPath?: string;
}

export interface ScaffoldResult {
  targetDir: string;
  config: DrmConfig;
  logoCopied: boolean;
  logoError?: string;
}

/**
 * The single scaffold implementation shared by the CLI's `init` command and
 * any GUI front-end: copies the desktop-app template into targetDir, writes
 * a validated drm-wrap.config.json, and personalizes package.json /
 * electron-builder.yml to match appName. Does not touch licensing — callers
 * decide when/whether to gate this (see require-license.ts for the CLI).
 */
export async function scaffoldProject(options: ScaffoldOptions): Promise<ScaffoldResult> {
  const targetDir = path.resolve(options.targetDir);
  const templateDir = resolveTemplateDir();

  await fs.ensureDir(targetDir);
  await fs.copy(templateDir, targetDir, {
    filter: (src) => {
      const base = path.basename(src);
      return base !== "node_modules" && base !== "dist" && base !== "release";
    },
  });

  const config = validateConfig(
    defaultConfig({
      appName: options.appName.trim() || "My Secure Portal",
      baseUrl: options.baseUrl.trim() || "https://example.com",
      features: options.features,
    })
  );

  saveConfig(config, targetDir);
  await personalizeGeneratedProject(targetDir, config.appName);

  let logoCopied = false;
  let logoError: string | undefined;
  if (options.logoPath && options.logoPath.trim().length > 0) {
    const resolvedLogoPath = path.resolve(options.logoPath.trim());
    if (await fs.pathExists(resolvedLogoPath)) {
      await fs.copy(resolvedLogoPath, path.join(targetDir, "public", "logo.png"));
      logoCopied = true;
    } else {
      logoError = `Logo file not found at ${resolvedLogoPath}`;
    }
  }

  return { targetDir, config, logoCopied, logoError };
}
